# Generated by Django 3.0.6 on 2020-05-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideos',
            fields=[
                ('VideoId', models.AutoField(primary_key=True, serialize=False)),
                ('fileTitle', models.CharField(default='keywords', max_length=100)),
                ('imageFile', models.FileField(default='Video.mp4', upload_to='excelList/')),
               
            ],
        ),
    ]
