# Generated by Django 3.0.6 on 2020-05-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideos',
            name='graphImage',
            field=models.ImageField(default='image.png', upload_to='data/'),
        ),
    ]
